// Shared input and result types used across repositories and the RAG pipeline.
// Note: SlabContent and QuestionAsked base types are generated by Prisma —
// import those directly from "../generated/prisma" instead.

import type { SlabContent } from "./generated/prisma";

// Input type for creating a new slab content record
export interface CreateSlabContent {
  title: string;
  chunk_text: string;
  embedding_vector?: number[];
  slab_url?: string;
}

// Input type for logging a new question
export interface CreateQuestionAsked {
  user_id: string;
  question_text: string;
}

// Vector search result with similarity score attached
export interface SlabContentWithSimilarity extends SlabContent {
  similarity: number;
}